CREATE TABLE [dbo].[ACCOUNTS] (
    [ACC_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [ACC_NAME]     NVARCHAR (50) NOT NULL,
    [ACC_PWD]      CHAR (16)     NOT NULL,
    [ACC_SECURITY] INT           NOT NULL,
    CONSTRAINT [PK_ACCOUNTS] PRIMARY KEY CLUSTERED ([ACC_ID] ASC),
    CONSTRAINT [IX_ACCOUNTS] UNIQUE NONCLUSTERED ([ACC_NAME] ASC)
);

