CREATE TABLE [dbo].[DEV_ERR] (
    [DEV_ID] INT NOT NULL,
    [ERR_ID] INT NOT NULL,
    CONSTRAINT [PK_DEV_ERR] PRIMARY KEY CLUSTERED ([DEV_ID] ASC, [ERR_ID] ASC),
    CONSTRAINT [FK_DEV_ERR_DEVICES] FOREIGN KEY ([DEV_ID]) REFERENCES [dbo].[DEVICES] ([DEV_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_DEV_ERR_ERRORS] FOREIGN KEY ([ERR_ID]) REFERENCES [dbo].[ERRORS] ([ERR_ID]) ON UPDATE CASCADE
);

