CREATE TABLE [dbo].[DEV_PARAM] (
    [DEV_PARAM_ID] INT        IDENTITY (1, 1) NOT NULL,
    [DEV_ID]       INT        NOT NULL,
    [PARAM_ID]     INT        NOT NULL,
    [VALUE]        FLOAT (53) NOT NULL,
    [TEST_TYPE_ID] INT        NOT NULL,
    CONSTRAINT [PK_DEV_PARAM_1] PRIMARY KEY CLUSTERED ([DEV_PARAM_ID] ASC),
    CONSTRAINT [FK_DEV_PARAM_DEVICES] FOREIGN KEY ([DEV_ID]) REFERENCES [dbo].[DEVICES] ([DEV_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_DEV_PARAM_PARAMS] FOREIGN KEY ([PARAM_ID]) REFERENCES [dbo].[PARAMS] ([PARAM_ID]) ON UPDATE CASCADE
);

