CREATE TABLE [dbo].[DEVICES] (
    [DEV_ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GROUP_ID]   INT              NOT NULL,
    [PROFILE_ID] UNIQUEIDENTIFIER NOT NULL,
    [CODE]       NVARCHAR (64)    NOT NULL,
    [SIL_N_1]    NVARCHAR (64)    NULL,
    [SIL_N_2]    NVARCHAR (64)    NULL,
    [TS]         DATETIME         NOT NULL,
    [USR]        NCHAR (16)       NOT NULL,
    [POS]        BIT              NOT NULL,
    [MME_CODE]   NVARCHAR (64)    NULL,
    CONSTRAINT [PK_DEVICES] PRIMARY KEY CLUSTERED ([DEV_ID] ASC),
    CONSTRAINT [FK_DEVICES_GROUPS] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[GROUPS] ([GROUP_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [IX_DEVICES] UNIQUE NONCLUSTERED ([GROUP_ID] ASC, [CODE] ASC, [POS] ASC, [PROFILE_ID] ASC)
);

