CREATE TABLE [dbo].[GROUPS] (
    [GROUP_ID]   INT        IDENTITY (1, 1) NOT NULL,
    [GROUP_NAME] NCHAR (32) NOT NULL,
    CONSTRAINT [PK_GROUPS] PRIMARY KEY CLUSTERED ([GROUP_ID] ASC),
    CONSTRAINT [IX_GROUPS] UNIQUE NONCLUSTERED ([GROUP_NAME] ASC)
);

