CREATE TABLE [dbo].[MME_CODES_TO_PROFILES] (
    [MME_CODE_ID] INT NOT NULL,
    [PROFILE_ID]  INT NOT NULL,
    CONSTRAINT [PK_MME_CODES_TO_PROFILES] PRIMARY KEY CLUSTERED ([MME_CODE_ID] ASC, [PROFILE_ID] ASC),
    CONSTRAINT [FK_MME_CODES_TO_PROFILES_MME_CODES] FOREIGN KEY ([MME_CODE_ID]) REFERENCES [dbo].[MME_CODES] ([MME_CODE_ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_MME_CODES_TO_PROFILES_PROFILES] FOREIGN KEY ([PROFILE_ID]) REFERENCES [dbo].[PROFILES] ([PROF_ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

