CREATE TABLE [dbo].[MME_CODES] (
    [MME_CODE_ID] INT           IDENTITY (1, 1) NOT NULL,
    [MME_CODE]    NVARCHAR (64) NOT NULL,
    CONSTRAINT [PK_MME_CODES] PRIMARY KEY CLUSTERED ([MME_CODE_ID] ASC)
);

