CREATE TABLE [dbo].[PARAMS] (
    [PARAM_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [PARAM_NAME]       CHAR (16)     NOT NULL,
    [PARAM_NAME_LOCAL] NVARCHAR (64) NOT NULL,
    [PARAM_IS_HIDE]    BIT           NOT NULL,
    CONSTRAINT [PK_PARAMS] PRIMARY KEY CLUSTERED ([PARAM_ID] ASC)
);

