CREATE TABLE [dbo].[PROFILES] (
    [PROF_ID]    INT              IDENTITY (1, 1) NOT NULL,
    [PROF_NAME]  NVARCHAR (32)    NOT NULL,
    [PROF_GUID]  UNIQUEIDENTIFIER NOT NULL,
    [PROF_TS]    DATETIME         NOT NULL,
    [PROF_VERS]  INT              NOT NULL,
    [IS_DELETED] BIT              NULL,
    CONSTRAINT [PK_PROFILES] PRIMARY KEY CLUSTERED ([PROF_ID] ASC),
    CONSTRAINT [IX_PROFILES] UNIQUE NONCLUSTERED ([PROF_GUID] ASC)
);

