CREATE TABLE [dbo].[PROF_COND] (
    [PROF_TESTTYPE_ID] INT       NOT NULL,
    [PROF_ID]          INT       NOT NULL,
    [COND_ID]          INT       NOT NULL,
    [VALUE]            CHAR (16) NOT NULL,
    CONSTRAINT [PK_PROF_COND] PRIMARY KEY CLUSTERED ([PROF_TESTTYPE_ID] ASC, [COND_ID] ASC, [PROF_ID] ASC),
    CONSTRAINT [FK_PROF_COND_PROF_COND] FOREIGN KEY ([COND_ID]) REFERENCES [dbo].[CONDITIONS] ([COND_ID]) ON UPDATE CASCADE,
    CONSTRAINT [FK_PROF_COND_PROF_TEST_TYPE] FOREIGN KEY ([PROF_TESTTYPE_ID]) REFERENCES [dbo].[PROF_TEST_TYPE] ([PTT_ID]),
    CONSTRAINT [FK_PROF_COND_PROFILES] FOREIGN KEY ([PROF_ID]) REFERENCES [dbo].[PROFILES] ([PROF_ID]) ON UPDATE CASCADE
);

