CREATE TABLE [dbo].[PROF_TEST_TYPE] (
    [PTT_ID]       INT IDENTITY (1, 1) NOT NULL,
    [PROF_ID]      INT NOT NULL,
    [TEST_TYPE_ID] INT NOT NULL,
    [ORD]          INT NULL,
    CONSTRAINT [PK_PROF_TEST_TYPE] PRIMARY KEY CLUSTERED ([PTT_ID] ASC),
    CONSTRAINT [FK_PROF_TEST_TYPE_PROFILES] FOREIGN KEY ([PROF_ID]) REFERENCES [dbo].[PROFILES] ([PROF_ID]) ON UPDATE CASCADE,
    CONSTRAINT [FK_PROF_TEST_TYPE_TEST_TYPE] FOREIGN KEY ([TEST_TYPE_ID]) REFERENCES [dbo].[TEST_TYPE] ([TEST_TYPE_ID]) ON UPDATE CASCADE,
    CONSTRAINT [IX_PROF_TEST_TYPE] UNIQUE NONCLUSTERED ([PROF_ID] ASC, [TEST_TYPE_ID] ASC, [ORD] ASC)
);

