CREATE TABLE [dbo].[PROF_PARAM] (
    [PROF_TESTTYPE_ID] INT        NOT NULL,
    [PROF_ID]          INT        NOT NULL,
    [PARAM_ID]         INT        NOT NULL,
    [MIN_VAL]          FLOAT (53) NULL,
    [MAX_VAL]          FLOAT (53) NULL,
    CONSTRAINT [PK_PROF_PARAM] PRIMARY KEY CLUSTERED ([PROF_TESTTYPE_ID] ASC, [PARAM_ID] ASC, [PROF_ID] ASC),
    CONSTRAINT [FK_PROF_PARAM_PARAMS] FOREIGN KEY ([PARAM_ID]) REFERENCES [dbo].[PARAMS] ([PARAM_ID]) ON UPDATE CASCADE,
    CONSTRAINT [FK_PROF_PARAM_PROFILES] FOREIGN KEY ([PROF_ID]) REFERENCES [dbo].[PROFILES] ([PROF_ID]) ON UPDATE CASCADE,
    CONSTRAINT [FK_PROF_PARAM_TEST_TYPE] FOREIGN KEY ([PROF_TESTTYPE_ID]) REFERENCES [dbo].[PROF_TEST_TYPE] ([PTT_ID])
);

