CREATE TABLE [dbo].[TEST_TYPE] (
    [TEST_TYPE_ID]   INT           NOT NULL,
    [TEST_TYPE_NAME] NVARCHAR (32) NOT NULL,
    CONSTRAINT [PK_TEST_TYPE] PRIMARY KEY CLUSTERED ([TEST_TYPE_ID] ASC)
);

