//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        public static string Adapter {
            get {
                return ResourceManager.GetString("Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional time, us.
        /// </summary>
        public static string AdditionalTime_us {
            get {
                return ResourceManager.GetString("AdditionalTime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All units are disabled.
        /// </summary>
        public static string AllUnitsAreDisabled {
            get {
                return ResourceManager.GetString("AllUnitsAreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amperage.
        /// </summary>
        public static string Amperage {
            get {
                return ResourceManager.GetString("Amperage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application start error.
        /// </summary>
        public static string ApplicationStartError {
            get {
                return ResourceManager.GetString("ApplicationStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATU.
        /// </summary>
        public static string ATU {
            get {
                return ResourceManager.GetString("ATU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I(PRSM), A.
        /// </summary>
        public static string AtuIPRSM {
            get {
                return ResourceManager.GetString("AtuIPRSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power, kW.
        /// </summary>
        public static string AtuPowerValueSet {
            get {
                return ResourceManager.GetString("AtuPowerValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmplitudePrePulseCurrent, mA.
        /// </summary>
        public static string AtuPrePulseValue {
            get {
                return ResourceManager.GetString("AtuPrePulseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRSM, kW.
        /// </summary>
        public static string AtuPRSM {
            get {
                return ResourceManager.GetString("AtuPRSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBR, V.
        /// </summary>
        public static string AtuUBR {
            get {
                return ResourceManager.GetString("AtuUBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U(PRSM), V.
        /// </summary>
        public static string AtuUPRSM {
            get {
                return ResourceManager.GetString("AtuUPRSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanel 2 temp, C.
        /// </summary>
        public static string BotTempName {
            get {
                return ResourceManager.GetString("BotTempName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BVT.
        /// </summary>
        public static string Bvt {
            get {
                return ResourceManager.GetString("Bvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not start test.
        /// </summary>
        public static string CanNotStartTest {
            get {
                return ResourceManager.GetString("CanNotStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamp.
        /// </summary>
        public static string Clamp {
            get {
                return ResourceManager.GetString("Clamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamp sliding device is out.
        /// </summary>
        public static string ClampSlidingDeviceIsOut {
            get {
                return ResourceManager.GetString("ClampSlidingDeviceIsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close safety hood.
        /// </summary>
        public static string CloseSafetyHood {
            get {
                return ResourceManager.GetString("CloseSafetyHood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commutation.
        /// </summary>
        public static string Commutation {
            get {
                return ResourceManager.GetString("Commutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commutation.
        /// </summary>
        public static string CommutationType {
            get {
                return ResourceManager.GetString("CommutationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commutation type.
        /// </summary>
        public static string CommutationTypeT {
            get {
                return ResourceManager.GetString("CommutationTypeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current, A.
        /// </summary>
        public static string Current_A {
            get {
                return ResourceManager.GetString("Current_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current limit, mA.
        /// </summary>
        public static string CurrentLimit_mA {
            get {
                return ResourceManager.GetString("CurrentLimit_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string Curve {
            get {
                return ResourceManager.GetString("Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string CurveFactor {
            get {
                return ResourceManager.GetString("CurveFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string DeviceClass {
            get {
                return ResourceManager.GetString("DeviceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class by RT.
        /// </summary>
        public static string DeviceRTClass {
            get {
                return ResourceManager.GetString("DeviceRTClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display timeout.
        /// </summary>
        public static string DisplayTimeout {
            get {
                return ResourceManager.GetString("DisplayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clamp.
        /// </summary>
        public static string DoClamp {
            get {
                return ResourceManager.GetString("DoClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclamp.
        /// </summary>
        public static string DoUnclamp {
            get {
                return ResourceManager.GetString("DoUnclamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dVdt.
        /// </summary>
        public static string dVdt {
            get {
                return ResourceManager.GetString("dVdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string DvdtConfirmation {
            get {
                return ResourceManager.GetString("DvdtConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationCount.
        /// </summary>
        public static string DvdtConfirmationCount {
            get {
                return ResourceManager.GetString("DvdtConfirmationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection.
        /// </summary>
        public static string DvdtDetection {
            get {
                return ResourceManager.GetString("DvdtDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage, V.
        /// </summary>
        public static string DvDtVoltage {
            get {
                return ResourceManager.GetString("DvDtVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoltageRate, V/mcs.
        /// </summary>
        public static string DvdtVoltageRate {
            get {
                return ResourceManager.GetString("DvdtVoltageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoltageRateLimit, V/mcs.
        /// </summary>
        public static string DvdtVoltageRateLimit {
            get {
                return ResourceManager.GetString("DvdtVoltageRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DvdtVoltageRateOffSet, V/mcs.
        /// </summary>
        public static string DvdtVoltageRateOffSet {
            get {
                return ResourceManager.GetString("DvdtVoltageRateOffSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error realisation.
        /// </summary>
        public static string ErrorRealisation {
            get {
                return ResourceManager.GetString("ErrorRealisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while parsing Profile config file.
        /// </summary>
        public static string ErrorWhileProfileParsing {
            get {
                return ResourceManager.GetString("ErrorWhileProfileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending results to server.
        /// </summary>
        public static string ErrorWriteResult {
            get {
                return ResourceManager.GetString("ErrorWriteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault.
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force, kN.
        /// </summary>
        public static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq rate, Hz.
        /// </summary>
        public static string FreqRate_Hz {
            get {
                return ResourceManager.GetString("FreqRate_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate.
        /// </summary>
        public static string Gate {
            get {
                return ResourceManager.GetString("Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway.
        /// </summary>
        public static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I, A.
        /// </summary>
        public static string Graph_IA {
            get {
                return ResourceManager.GetString("Graph_IA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I, mA.
        /// </summary>
        public static string Graph_ImA {
            get {
                return ResourceManager.GetString("Graph_ImA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Graph_Time {
            get {
                return ResourceManager.GetString("Graph_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time, ms.
        /// </summary>
        public static string Graph_TimeMs {
            get {
                return ResourceManager.GetString("Graph_TimeMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time, us.
        /// </summary>
        public static string Graph_TimeUs {
            get {
                return ResourceManager.GetString("Graph_TimeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string Graph_V {
            get {
                return ResourceManager.GetString("Graph_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V, I.
        /// </summary>
        public static string Graph_VI {
            get {
                return ResourceManager.GetString("Graph_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group list.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening current, A.
        /// </summary>
        public static string HeatCurrent_A {
            get {
                return ResourceManager.GetString("HeatCurrent_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening time, us.
        /// </summary>
        public static string HeatTime_us {
            get {
                return ResourceManager.GetString("HeatTime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height, mm.
        /// </summary>
        public static string Height_Prof {
            get {
                return ResourceManager.GetString("Height_Prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding current.
        /// </summary>
        public static string HoldingCurrent {
            get {
                return ResourceManager.GetString("HoldingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding strike current.
        /// </summary>
        public static string HoldingStrikeCurrent {
            get {
                return ResourceManager.GetString("HoldingStrikeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDRM, mA.
        /// </summary>
        public static string Idrm_mA {
            get {
                return ResourceManager.GetString("Idrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDSM, mA.
        /// </summary>
        public static string IDSM_mA {
            get {
                return ResourceManager.GetString("IDSM_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGT, mA.
        /// </summary>
        public static string Igt_mA {
            get {
                return ResourceManager.GetString("Igt_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IH.
        /// </summary>
        public static string IH {
            get {
                return ResourceManager.GetString("IH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding current, mA.
        /// </summary>
        public static string IHIh {
            get {
                return ResourceManager.GetString("IHIh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force current, A.
        /// </summary>
        public static string IHItm {
            get {
                return ResourceManager.GetString("IHItm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ih, mA.
        /// </summary>
        public static string Iholding_mA {
            get {
                return ResourceManager.GetString("Iholding_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il, mA.
        /// </summary>
        public static string Ilatching_mA {
            get {
                return ResourceManager.GetString("Ilatching_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRRM, mA.
        /// </summary>
        public static string Irrm_mA {
            get {
                return ResourceManager.GetString("Irrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRSM, mA.
        /// </summary>
        public static string IRSM_mA {
            get {
                return ResourceManager.GetString("IRSM_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        public static string IsHeatEnabled {
            get {
                return ResourceManager.GetString("IsHeatEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITM, A.
        /// </summary>
        public static string Itm_A {
            get {
                return ResourceManager.GetString("Itm_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latching current.
        /// </summary>
        public static string LatchingCurrent {
            get {
                return ResourceManager.GetString("LatchingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mA.
        /// </summary>
        public static string mA {
            get {
                return ResourceManager.GetString("mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. IDRM, mA.
        /// </summary>
        public static string MaxIdrm_mA {
            get {
                return ResourceManager.GetString("MaxIdrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. IGT, mA.
        /// </summary>
        public static string MaxIgt_mA {
            get {
                return ResourceManager.GetString("MaxIgt_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. IH, mA.
        /// </summary>
        public static string MaxIh_mA {
            get {
                return ResourceManager.GetString("MaxIh_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. IL, mA.
        /// </summary>
        public static string MaxIl_mA {
            get {
                return ResourceManager.GetString("MaxIl_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. IRRM, mA.
        /// </summary>
        public static string MaxIrrm_mA {
            get {
                return ResourceManager.GetString("MaxIrrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Rg, Ohm.
        /// </summary>
        public static string MaxResistance_Ohm {
            get {
                return ResourceManager.GetString("MaxResistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. VGT, V.
        /// </summary>
        public static string MaxVgt_V {
            get {
                return ResourceManager.GetString("MaxVgt_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. VTM, V.
        /// </summary>
        public static string MaxVtm_V {
            get {
                return ResourceManager.GetString("MaxVtm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height measuring.
        /// </summary>
        public static string MeasureDialog_Title {
            get {
                return ResourceManager.GetString("MeasureDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, the changes will not be saved.
        /// </summary>
        public static string MessageErrorSaveTestFault {
            get {
                return ResourceManager.GetString("MessageErrorSaveTestFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. VDRM, V.
        /// </summary>
        public static string MinVdrm_V {
            get {
                return ResourceManager.GetString("MinVdrm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. VRRM, V.
        /// </summary>
        public static string MinVrrm_V {
            get {
                return ResourceManager.GetString("MinVrrm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move clamp sliding device to home.
        /// </summary>
        public static string MoveClampSlidingDeviceToHome {
            get {
                return ResourceManager.GetString("MoveClampSlidingDeviceToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not correct.
        /// </summary>
        public static string NonCorrect {
            get {
                return ResourceManager.GetString("NonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator in Build Mode.
        /// </summary>
        public static string OperatorBuildMode {
            get {
                return ResourceManager.GetString("OperatorBuildMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string OperatorMode {
            get {
                return ResourceManager.GetString("OperatorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type.
        /// </summary>
        public static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PE_logo_1024 {
            get {
                object obj = ResourceManager.GetObject("PE_logo_1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate time, ms.
        /// </summary>
        public static string PlateTime_ms {
            get {
                return ResourceManager.GetString("PlateTime_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position 1.
        /// </summary>
        public static string Position_1 {
            get {
                return ResourceManager.GetString("Position_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position 2.
        /// </summary>
        public static string Position_2 {
            get {
                return ResourceManager.GetString("Position_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power line Freq, Hz.
        /// </summary>
        public static string PowerLineFrequency_Hz {
            get {
                return ResourceManager.GetString("PowerLineFrequency_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing options:.
        /// </summary>
        public static string PrintingOptions {
            get {
                return ResourceManager.GetString("PrintingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile load error.
        /// </summary>
        public static string Profile_load_error {
            get {
                return ResourceManager.GetString("Profile_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load profiles from company server. Local copy is used temporary. Error {0}.
        /// </summary>
        public static string Profile_load_error_ex {
            get {
                return ResourceManager.GetString("Profile_load_error_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Not Changed.
        /// </summary>
        public static string ProfileNotChanged {
            get {
                return ResourceManager.GetString("ProfileNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not synced.
        /// </summary>
        public static string ProfileNotSynced {
            get {
                return ResourceManager.GetString("ProfileNotSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles not editable in sync with central server.
        /// </summary>
        public static string ProfilePageToolTip {
            get {
                return ResourceManager.GetString("ProfilePageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile was untied from mme code.
        /// </summary>
        public static string ProfileWasUntied {
            get {
                return ResourceManager.GetString("ProfileWasUntied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job number.
        /// </summary>
        public static string PsdJob {
            get {
                return ResourceManager.GetString("PsdJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device serial number.
        /// </summary>
        public static string PsdSerialNumber {
            get {
                return ResourceManager.GetString("PsdSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pse job.
        /// </summary>
        public static string PseJob {
            get {
                return ResourceManager.GetString("PseJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSE number.
        /// </summary>
        public static string PseNumber {
            get {
                return ResourceManager.GetString("PseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull stop button.
        /// </summary>
        public static string PullStopButton {
            get {
                return ResourceManager.GetString("PullStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anode current.
        /// </summary>
        public static string PureVgt {
            get {
                return ResourceManager.GetString("PureVgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QrrTq.
        /// </summary>
        public static string QrrTq {
            get {
                return ResourceManager.GetString("QrrTq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dIDC/dt, A/us.
        /// </summary>
        public static string QrrTqDCFactFallRate {
            get {
                return ResourceManager.GetString("QrrTqDCFactFallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct current fall rate, A/us.
        /// </summary>
        public static string QrrTqDCFallRate {
            get {
                return ResourceManager.GetString("QrrTqDCFallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct current pulse duration, us.
        /// </summary>
        public static string QrrTqDCPulseWidth {
            get {
                return ResourceManager.GetString("QrrTqDCPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct current rise rate, A/us.
        /// </summary>
        public static string QrrTqDCRiseRate {
            get {
                return ResourceManager.GetString("QrrTqDCRiseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct current amplitude, A.
        /// </summary>
        public static string QrrTqDirectCurrent {
            get {
                return ResourceManager.GetString("QrrTqDirectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDC, A.
        /// </summary>
        public static string QrrTqIdc {
            get {
                return ResourceManager.GetString("QrrTqIdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRR, A.
        /// </summary>
        public static string QrrTqIrr {
            get {
                return ResourceManager.GetString("QrrTqIrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string QrrTqMode {
            get {
                return ResourceManager.GetString("QrrTqMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off-state voltage, V.
        /// </summary>
        public static string QrrTqOffStateVoltage {
            get {
                return ResourceManager.GetString("QrrTqOffStateVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma, V.
        /// </summary>
        public static string QrrTqOffStateVoltageTittleShort {
            get {
                return ResourceManager.GetString("QrrTqOffStateVoltageTittleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off-state voltage rise rate, V/us.
        /// </summary>
        public static string QrrTqOsvRate {
            get {
                return ResourceManager.GetString("QrrTqOsvRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dU/dt, V/us.
        /// </summary>
        public static string QrrTqOsvRateTittleShort {
            get {
                return ResourceManager.GetString("QrrTqOsvRateTittleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRR, uC.
        /// </summary>
        public static string QrrTqQrr {
            get {
                return ResourceManager.GetString("QrrTqQrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tq, us.
        /// </summary>
        public static string QrrTqTq {
            get {
                return ResourceManager.GetString("QrrTqTq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRR, us.
        /// </summary>
        public static string QrrTqTrr {
            get {
                return ResourceManager.GetString("QrrTqTrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Trr by 90%-50% method.
        /// </summary>
        public static string QrrTqTrrMeasureBy9050Method {
            get {
                return ResourceManager.GetString("QrrTqTrrMeasureBy9050Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R A-C.
        /// </summary>
        public static string RAC {
            get {
                return ResourceManager.GetString("RAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R, MOhm.
        /// </summary>
        public static string RACResultR {
            get {
                return ResourceManager.GetString("RACResultR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC voltage value for resistance measurement, V.
        /// </summary>
        public static string RACResVoltage {
            get {
                return ResourceManager.GetString("RACResVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        public static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp up, V/ms.
        /// </summary>
        public static string Rampup_Vms {
            get {
                return ResourceManager.GetString("Rampup_Vms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Read only.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg, Ohm.
        /// </summary>
        public static string Resistance_Ohm {
            get {
                return ResourceManager.GetString("Resistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results will not be saved.
        /// </summary>
        public static string ResultsWillNotBeSaved {
            get {
                return ResourceManager.GetString("ResultsWillNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety circuit is open.
        /// </summary>
        public static string SafetyCircuitIsOpen {
            get {
                return ResourceManager.GetString("SafetyCircuitIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety perimeter is broken!.
        /// </summary>
        public static string SafetyOpticalAlarm {
            get {
                return ResourceManager.GetString("SafetyOpticalAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on ex the  safety.
        /// </summary>
        public static string SafetySystemExternal {
            get {
                return ResourceManager.GetString("SafetySystemExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on in the  safety.
        /// </summary>
        public static string SafetySystemInternal {
            get {
                return ResourceManager.GetString("SafetySystemInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off the safety.
        /// </summary>
        public static string SafetySystemOff {
            get {
                return ResourceManager.GetString("SafetySystemOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on the  safety.
        /// </summary>
        public static string SafetySystemOn {
            get {
                return ResourceManager.GetString("SafetySystemOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work mode.
        /// </summary>
        public static string SelectWorkModePageTitle {
            get {
                return ResourceManager.GetString("SelectWorkModePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selftest.
        /// </summary>
        public static string Selftest {
            get {
                return ResourceManager.GetString("Selftest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviceman.
        /// </summary>
        public static string ServicemanMode {
            get {
                return ResourceManager.GetString("ServicemanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        public static string SetCool {
            get {
                return ResourceManager.GetString("SetCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        public static string SetTemp {
            get {
                return ResourceManager.GetString("SetTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting temperature, C.
        /// </summary>
        public static string SettingTemperatureName {
            get {
                return ResourceManager.GetString("SettingTemperatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinus.
        /// </summary>
        public static string Sinus {
            get {
                return ResourceManager.GetString("Sinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialMeasure.
        /// </summary>
        public static string SpecialMeasureMode {
            get {
                return ResourceManager.GetString("SpecialMeasureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start voltage, V.
        /// </summary>
        public static string StartVoltage_V {
            get {
                return ResourceManager.GetString("StartVoltage_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop button is pressed.
        /// </summary>
        public static string StopButtonIsPressed {
            get {
                return ResourceManager.GetString("StopButtonIsPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technitian.
        /// </summary>
        public static string Technitian {
            get {
                return ResourceManager.GetString("Technitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp, C.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test type.
        /// </summary>
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tGD, us.
        /// </summary>
        public static string TGD {
            get {
                return ResourceManager.GetString("TGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tGT, us.
        /// </summary>
        public static string TGT {
            get {
                return ResourceManager.GetString("TGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time, us.
        /// </summary>
        public static string Time_us {
            get {
                return ResourceManager.GetString("Time_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanel 1 temp, C.
        /// </summary>
        public static string TopTempName {
            get {
                return ResourceManager.GetString("TopTempName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOU.
        /// </summary>
        public static string TOU {
            get {
                return ResourceManager.GetString("TOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amperage (ITM), A.
        /// </summary>
        public static string TOUITM {
            get {
                return ResourceManager.GetString("TOUITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full scale.
        /// </summary>
        public static string UseFullScale {
            get {
                return ResourceManager.GetString("UseFullScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSQ method.
        /// </summary>
        public static string UseLsqMethod {
            get {
                return ResourceManager.GetString("UseLsqMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile.
        /// </summary>
        public static string UserPage_Title {
            get {
                return ResourceManager.GetString("UserPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string UserTestPage_Title {
            get {
                return ResourceManager.GetString("UserTestPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDSM/URSM.
        /// </summary>
        public static string UseUdsmUrsm {
            get {
                return ResourceManager.GetString("UseUdsmUrsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDRM, V.
        /// </summary>
        public static string VdrmV {
            get {
                return ResourceManager.GetString("VdrmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDSM, V.
        /// </summary>
        public static string VDSM_V {
            get {
                return ResourceManager.GetString("VDSM_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VGT.
        /// </summary>
        public static string Vgt {
            get {
                return ResourceManager.GetString("Vgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VGT, mV.
        /// </summary>
        public static string VgtmV {
            get {
                return ResourceManager.GetString("VgtmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VGT, V.
        /// </summary>
        public static string VgtV {
            get {
                return ResourceManager.GetString("VgtV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V / ms.
        /// </summary>
        public static string Vms {
            get {
                return ResourceManager.GetString("Vms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage D, V.
        /// </summary>
        public static string VoltageLimitD_V {
            get {
                return ResourceManager.GetString("VoltageLimitD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage R, V.
        /// </summary>
        public static string VoltageLimitR_V {
            get {
                return ResourceManager.GetString("VoltageLimitR_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRRM, V.
        /// </summary>
        public static string VrrmV {
            get {
                return ResourceManager.GetString("VrrmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRSM, V.
        /// </summary>
        public static string VRSM_V {
            get {
                return ResourceManager.GetString("VRSM_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static losses.
        /// </summary>
        public static string Vtm {
            get {
                return ResourceManager.GetString("Vtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTM, V.
        /// </summary>
        public static string VtmV {
            get {
                return ResourceManager.GetString("VtmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string WelcomePage_Title {
            get {
                return ResourceManager.GetString("WelcomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
