//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class SettingsUI : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsUI defaultInstance = ((SettingsUI)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsUI())));
        
        public static SettingsUI Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ComplexPartsIsDisabled {
            get {
                return ((string)(this["ComplexPartsIsDisabled"]));
            }
            set {
                this["ComplexPartsIsDisabled"] = value;
            }
        }
    }
}
