//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.SQLDatabaseClient.EntityAccounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int ACC_ID { get; set; }
        public string ACC_NAME { get; set; }
        public string ACC_PWD { get; set; }
        public Security ACC_SECURITY { get; set; }
    }
}
