//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.EntityDataDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CONDITION
    {
        public CONDITION()
        {
            this.PROF_COND = new HashSet<PROF_COND>();
        }
    
        [Key]
        public int COND_ID { get; set; }
        public string COND_NAME { get; set; }
        public string COND_NAME_LOCAL { get; set; }
        public bool COND_IS_TECH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROF_COND> PROF_COND { get; set; }
    }
}
