//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.EntityDataDB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVICE()
        {
            this.DEV_PARAM = new HashSet<DEV_PARAM>();
        }
    
        [Key]
        public int DEV_ID { get; set; }
        public int GROUP_ID { get; set; }
        public System.Guid PROFILE_ID { get; set; }
        public string CODE { get; set; }
        public string SIL_N_1 { get; set; }
        public string SIL_N_2 { get; set; }
        public System.DateTime TS { get; set; }
        public string USR { get; set; }
        public bool POS { get; set; }
        public string MME_CODE { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        
        public virtual ICollection<DEV_PARAM> DEV_PARAM { get; set; }



        public virtual ICollection<DEV_ERR> DEV_ERRS { get; set; } = new HashSet<DEV_ERR>();
    }
}
