//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.dbViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.dbViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITAV.
        /// </summary>
        public static string AverageCurrent {
            get {
                return ResourceManager.GetString("AverageCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user permissions.
        /// </summary>
        public static string BitCalculator {
            get {
                return ResourceManager.GetString("BitCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build assembly protocol.
        /// </summary>
        public static string BuildAssemblyProtocol {
            get {
                return ResourceManager.GetString("BuildAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change device status.
        /// </summary>
        public static string ChangeDeviceStatus {
            get {
                return ResourceManager.GetString("ChangeDeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject num.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of non match.
        /// </summary>
        public static string CodeOfNonMatch {
            get {
                return ResourceManager.GetString("CodeOfNonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сomment to add.
        /// </summary>
        public static string CommentToAdd {
            get {
                return ResourceManager.GetString("CommentToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; and all its saved values ​​will be permanently deleted. Proceed?.
        /// </summary>
        public static string ConfirmationMessForDeleteManualInputParam {
            get {
                return ResourceManager.GetString("ConfirmationMessForDeleteManualInputParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructive.
        /// </summary>
        public static string Constructive {
            get {
                return ResourceManager.GetString("Constructive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create parameter.
        /// </summary>
        public static string CreateParameter {
            get {
                return ResourceManager.GetString("CreateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create value of manually entered parameter.
        /// </summary>
        public static string CreateValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("CreateValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data will not be saved..
        /// </summary>
        public static string DataWillNotBeSaved {
            get {
                return ResourceManager.GetString("DataWillNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all filters.
        /// </summary>
        public static string DeleteAllFilters {
            get {
                return ResourceManager.GetString("DeleteAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete parameter.
        /// </summary>
        public static string DeleteParameter {
            get {
                return ResourceManager.GetString("DeleteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete permissions of user.
        /// </summary>
        public static string DeletePermissionsOfUser {
            get {
                return ResourceManager.GetString("DeletePermissionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete value of manually entered parameter.
        /// </summary>
        public static string DeleteValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("DeleteValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in english.
        /// </summary>
        public static string DescrEN {
            get {
                return ResourceManager.GetString("DescrEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in russian.
        /// </summary>
        public static string DescrRU {
            get {
                return ResourceManager.GetString("DescrRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string DeviceClass {
            get {
                return ResourceManager.GetString("DeviceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device comments.
        /// </summary>
        public static string DeviceComments {
            get {
                return ResourceManager.GetString("DeviceComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device identificator.
        /// </summary>
        public static string DevID {
            get {
                return ResourceManager.GetString("DevID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop of the assembly protocol.
        /// </summary>
        public static string DropAssemblyProtocol {
            get {
                return ResourceManager.GetString("DropAssemblyProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit parameter.
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value of manually entered parameter.
        /// </summary>
        public static string EditValueOfManuallyEnteredParameter {
            get {
                return ResourceManager.GetString("EditValueOfManuallyEnteredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data from database.
        /// </summary>
        public static string LoadDataFromDataBaseFault {
            get {
                return ResourceManager.GetString("LoadDataFromDataBaseFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with the data collected by means of MME hardware in the central database.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage by self permissions.
        /// </summary>
        public static string ManageBySelfPermissions {
            get {
                return ResourceManager.GetString("ManageBySelfPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage permissions of user.
        /// </summary>
        public static string ManagePermissionsOfUser {
            get {
                return ResourceManager.GetString("ManagePermissionsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual input param editor.
        /// </summary>
        public static string ManualInputParamEditor {
            get {
                return ResourceManager.GetString("ManualInputParamEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually entered parameters.
        /// </summary>
        public static string ManualInputParams {
            get {
                return ResourceManager.GetString("ManualInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code MME.
        /// </summary>
        public static string MmeCode {
            get {
                return ResourceManager.GetString("MmeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editing object selected..
        /// </summary>
        public static string NoEditingObjectSelected {
            get {
                return ResourceManager.GetString("NoEditingObjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object for delete not selected..
        /// </summary>
        public static string ObjectForDeleteNotSelected {
            get {
                return ResourceManager.GetString("ObjectForDeleteNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name not defined..
        /// </summary>
        public static string ParameterNameNotDefined {
            get {
                return ResourceManager.GetString("ParameterNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect or the DC user &apos;{0}&apos; does not exist.
        /// </summary>
        public static string PasswordIsIncorrect {
            get {
                return ResourceManager.GetString("PasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile identificator.
        /// </summary>
        public static string ProfileID {
            get {
                return ResourceManager.GetString("ProfileID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and create comment.
        /// </summary>
        public static string ReadCreateComment {
            get {
                return ResourceManager.GetString("ReadCreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading comments.
        /// </summary>
        public static string ReadingComments {
            get {
                return ResourceManager.GetString("ReadingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record date.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records shown: .
        /// </summary>
        public static string RecordsShown {
            get {
                return ResourceManager.GetString("RecordsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source data for building a report is empty. Report generation does not make sense..
        /// </summary>
        public static string ReportCannotBeGenerated {
            get {
                return ResourceManager.GetString("ReportCannotBeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositioning the device.
        /// </summary>
        public static string RepositioningTheDevice {
            get {
                return ResourceManager.GetString("RepositioningTheDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select DC user.
        /// </summary>
        public static string SelectDCUser {
            get {
                return ResourceManager.GetString("SelectDCUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select devices.
        /// </summary>
        public static string SelectDevices {
            get {
                return ResourceManager.GetString("SelectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected parameter &apos;{0}&apos; is not deletable..
        /// </summary>
        public static string SelectedParameterIsNotDeletable {
            get {
                return ResourceManager.GetString("SelectedParameterIsNotDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected parameter &apos;{0}&apos; is not editable. The value of this parameter can be obtained by measuring on equipment..
        /// </summary>
        public static string SelectedParameterIsNotEditable {
            get {
                return ResourceManager.GetString("SelectedParameterIsNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user as admin.
        /// </summary>
        public static string SetAdministrator {
            get {
                return ResourceManager.GetString("SetAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set user permissions.
        /// </summary>
        public static string SetUserPermissions {
            get {
                return ResourceManager.GetString("SetUserPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnity.
        /// </summary>
        public static string SiOmnity {
            get {
                return ResourceManager.GetString("SiOmnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        public static string SiType {
            get {
                return ResourceManager.GetString("SiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition of Temperature.
        /// </summary>
        public static string TemperatureCondition {
            get {
                return ResourceManager.GetString("TemperatureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Ts {
            get {
                return ResourceManager.GetString("Ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um.
        /// </summary>
        public static string Um {
            get {
                return ResourceManager.GetString("Um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit measure is not defined..
        /// </summary>
        public static string UnitMeasureIsNotDefined {
            get {
                return ResourceManager.GetString("UnitMeasureIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User credentials.
        /// </summary>
        public static string UserCredentials {
            get {
                return ResourceManager.GetString("UserCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; is not an application user &apos;{1}&apos;.
        /// </summary>
        public static string UserIisNotAnApplicationUser {
            get {
                return ResourceManager.GetString("UserIisNotAnApplicationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User selected.
        /// </summary>
        public static string UserSelected {
            get {
                return ResourceManager.GetString("UserSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Usr {
            get {
                return ResourceManager.GetString("Usr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of manually entered parameter.
        /// </summary>
        public static string ValueOfManuallyEnteredParam {
            get {
                return ResourceManager.GetString("ValueOfManuallyEnteredParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with comments.
        /// </summary>
        public static string WorkWithComments {
            get {
                return ResourceManager.GetString("WorkWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with manually entered parameters.
        /// </summary>
        public static string WorkWithManualInputParams {
            get {
                return ResourceManager.GetString("WorkWithManualInputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with value of manually entered parameter.
        /// </summary>
        public static string WorkWithValueOfManualInputParam {
            get {
                return ResourceManager.GetString("WorkWithValueOfManualInputParam", resourceCulture);
            }
        }
    }
}
