//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception {0} during callback action: {1}.
        /// </summary>
        internal static string Error_BroadcastCommunication_Exception_during_callback_action {
            get {
                return ResourceManager.GetString("Error_BroadcastCommunication_Exception_during_callback_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation - {3}, Node - {0}, Address - {1}, Message - {2}.
        /// </summary>
        internal static string Error_IOAdapter_Operation_Node_Address_Message {
            get {
                return ResourceManager.GetString("Error_IOAdapter_Operation_Node_Address_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation - {4}, Node - {0}, Address - {1}, Value - {2}, Message - {3}.
        /// </summary>
        internal static string Error_IOAdapter_Operation_Node_Address_Value_Message {
            get {
                return ResourceManager.GetString("Error_IOAdapter_Operation_Node_Address_Value_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string Error_LogicContainer_Exception {
            get {
                return ResourceManager.GetString("Error_LogicContainer_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main testing, state - {0}, exception - {1}.
        /// </summary>
        internal static string Error_LogicContainer_Main_testing_state_exception {
            get {
                return ResourceManager.GetString("Error_LogicContainer_Main_testing_state_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        internal static string Error_Program_Application_error {
            get {
                return ResourceManager.GetString("Error_Program_Application_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All disconnected.
        /// </summary>
        internal static string Log_LogicContainer_All_disconnected {
            get {
                return ResourceManager.GetString("Log_LogicContainer_All_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Log_LogicContainer_Connected {
            get {
                return ResourceManager.GetString("Log_LogicContainer_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state: {0}.
        /// </summary>
        internal static string Log_LogicContainer_Connection_state {
            get {
                return ResourceManager.GetString("Log_LogicContainer_Connection_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Log_LogicContainer_Failed {
            get {
                return ResourceManager.GetString("Log_LogicContainer_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main test manual stop.
        /// </summary>
        internal static string Log_LogicContainer_Main_test_manual_stop {
            get {
                return ResourceManager.GetString("Log_LogicContainer_Main_test_manual_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested block modes: Gate - {0}, SL - {1}, BVT - {2}, Clamp - {3}, dVdt - {4}, ATU - {5}, QrrTq - {6}, RAC - {7}, IH - {8}.
        /// </summary>
        internal static string Log_LogicContainer_Requested_block_modes {
            get {
                return ResourceManager.GetString("Log_LogicContainer_Requested_block_modes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application closed.
        /// </summary>
        internal static string Log_SystemHost_Application_closed {
            get {
                return ResourceManager.GetString("Log_SystemHost_Application_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application started.
        /// </summary>
        internal static string Log_SystemHost_Application_started {
            get {
                return ResourceManager.GetString("Log_SystemHost_Application_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control service is listening.
        /// </summary>
        internal static string Log_SystemHost_Control_service_is_listening {
            get {
                return ResourceManager.GetString("Log_SystemHost_Control_service_is_listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service is listening.
        /// </summary>
        internal static string Log_SystemHost_Database_service_is_listening {
            get {
                return ResourceManager.GetString("Log_SystemHost_Database_service_is_listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while closing {0}: {1}.
        /// </summary>
        internal static string Log_SystemHost_Error_while_closing {
            get {
                return ResourceManager.GetString("Log_SystemHost_Error_while_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance service is listening.
        /// </summary>
        internal static string Log_SystemHost_Maintenance_service_is_listening {
            get {
                return ResourceManager.GetString("Log_SystemHost_Maintenance_service_is_listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result journal opened.
        /// </summary>
        internal static string Log_SystemHost_Result_journal_opened {
            get {
                return ResourceManager.GetString("Log_SystemHost_Result_journal_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Program_Main_Exit {
            get {
                return ResourceManager.GetString("Program_Main_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety circuit is open.
        /// </summary>
        internal static string SafetyCircuitIsOpen {
            get {
                return ResourceManager.GetString("SafetyCircuitIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ServiceIcon {
            get {
                object obj = ResourceManager.GetObject("ServiceIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
