//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.ProfileBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.ProfileBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адаптер.
        /// </summary>
        public static string Adapter {
            get {
                return ResourceManager.GetString("Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. время, мкс.
        /// </summary>
        public static string AdditionalTime_us {
            get {
                return ResourceManager.GetString("AdditionalTime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все модули отключены.
        /// </summary>
        public static string AllUnitsAreDisabled {
            get {
                return ResourceManager.GetString("AllUnitsAreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при запуске приложения.
        /// </summary>
        public static string ApplicationStartError {
            get {
                return ResourceManager.GetString("ApplicationStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лавина.
        /// </summary>
        public static string Atu {
            get {
                return ResourceManager.GetString("Atu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мощность, кВт.
        /// </summary>
        public static string AtuPowerValueSet {
            get {
                return ResourceManager.GetString("AtuPowerValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амплитуда предв. импульса тока, мА.
        /// </summary>
        public static string AtuPrePulseValue {
            get {
                return ResourceManager.GetString("AtuPrePulseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Классификатор.
        /// </summary>
        public static string Bvt {
            get {
                return ResourceManager.GetString("Bvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калибровка.
        /// </summary>
        public static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызвать.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно начать тест.
        /// </summary>
        public static string CanNotStartTest {
            get {
                return ResourceManager.GetString("CanNotStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отметить все.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пресс.
        /// </summary>
        public static string Clamp {
            get {
                return ResourceManager.GetString("Clamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закройте защитную заслонку.
        /// </summary>
        public static string CloseSafetyHood {
            get {
                return ResourceManager.GetString("CloseSafetyHood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блок коммутации.
        /// </summary>
        public static string Commutation {
            get {
                return ResourceManager.GetString("Commutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коммутация.
        /// </summary>
        public static string CommutationType {
            get {
                return ResourceManager.GetString("CommutationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип коммутации.
        /// </summary>
        public static string CommutationTypeT {
            get {
                return ResourceManager.GetString("CommutationTypeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключиться.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верно.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток, А.
        /// </summary>
        public static string Current_A {
            get {
                return ResourceManager.GetString("Current_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток, мА.
        /// </summary>
        public static string CurrentLimit_mA {
            get {
                return ResourceManager.GetString("CurrentLimit_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-кривая.
        /// </summary>
        public static string Curve {
            get {
                return ResourceManager.GetString("Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коэффициент.
        /// </summary>
        public static string CurveFactor {
            get {
                return ResourceManager.GetString("CurveFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказчик:.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип п-ра:.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сер. номер прибора.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямой.
        /// </summary>
        public static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключить.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключен.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисплей.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таймаут дисплея.
        /// </summary>
        public static string DisplayTimeout {
            get {
                return ResourceManager.GetString("DisplayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зажать.
        /// </summary>
        public static string DoClamp {
            get {
                return ResourceManager.GetString("DoClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разжать.
        /// </summary>
        public static string DoUnclamp {
            get {
                return ResourceManager.GetString("DoUnclamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dVdt.
        /// </summary>
        public static string dVdt {
            get {
                return ResourceManager.GetString("dVdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверджение.
        /// </summary>
        public static string DvdtConfirmation {
            get {
                return ResourceManager.GetString("DvdtConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число подтверждений.
        /// </summary>
        public static string DvdtConfirmationCount {
            get {
                return ResourceManager.GetString("DvdtConfirmationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определение.
        /// </summary>
        public static string DvdtDetection {
            get {
                return ResourceManager.GetString("DvdtDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напряжение, В.
        /// </summary>
        public static string DvDtVoltage {
            get {
                return ResourceManager.GetString("DvDtVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скор. роста, В/мкс.
        /// </summary>
        public static string DvdtVoltageRate {
            get {
                return ResourceManager.GetString("DvdtVoltageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Огр. скор. роста, В/мкс.
        /// </summary>
        public static string DvdtVoltageRateLimit {
            get {
                return ResourceManager.GetString("DvdtVoltageRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+) к скор. роста, В/мкс.
        /// </summary>
        public static string DvdtVoltageRateOffSet {
            get {
                return ResourceManager.GetString("DvdtVoltageRateOffSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключить.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при чтении конфигурационного файла профилей.
        /// </summary>
        public static string ErrorWhileProfileParsing {
            get {
                return ResourceManager.GetString("ErrorWhileProfileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка отправки.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усилие, кН.
        /// </summary>
        public static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота имп., Гц.
        /// </summary>
        public static string FreqRate_Hz {
            get {
                return ResourceManager.GetString("FreqRate_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота, Гц.
        /// </summary>
        public static string Frequency_Hz {
            get {
                return ResourceManager.GetString("Frequency_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Gate {
            get {
                return ResourceManager.GetString("Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлюз.
        /// </summary>
        public static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I, мА.
        /// </summary>
        public static string Graph_ImA {
            get {
                return ResourceManager.GetString("Graph_ImA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время, мс.
        /// </summary>
        public static string Graph_TimeMs {
            get {
                return ResourceManager.GetString("Graph_TimeMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время, мкс.
        /// </summary>
        public static string Graph_TimeUs {
            get {
                return ResourceManager.GetString("Graph_TimeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        public static string Graph_V {
            get {
                return ResourceManager.GetString("Graph_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U, I.
        /// </summary>
        public static string Graph_VI {
            get {
                return ResourceManager.GetString("Graph_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список партий.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аппаратная часть.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток откр., А.
        /// </summary>
        public static string HeatCurrent_A {
            get {
                return ResourceManager.GetString("HeatCurrent_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время откр., мкс.
        /// </summary>
        public static string HeatTime_us {
            get {
                return ResourceManager.GetString("HeatTime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота, мм.
        /// </summary>
        public static string Height_Prof {
            get {
                return ResourceManager.GetString("Height_Prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток удержания.
        /// </summary>
        public static string HoldingCurrent {
            get {
                return ResourceManager.GetString("HoldingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. импульс.
        /// </summary>
        public static string HoldingStrikeCurrent {
            get {
                return ResourceManager.GetString("HoldingStrikeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDRM, мА.
        /// </summary>
        public static string Idrm_mA {
            get {
                return ResourceManager.GetString("Idrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGT, мА.
        /// </summary>
        public static string Igt_mA {
            get {
                return ResourceManager.GetString("Igt_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ih, мА.
        /// </summary>
        public static string Iholding_mA {
            get {
                return ResourceManager.GetString("Iholding_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il, мА.
        /// </summary>
        public static string Ilatching_mA {
            get {
                return ResourceManager.GetString("Ilatching_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRRM, мА.
        /// </summary>
        public static string Irrm_mA {
            get {
                return ResourceManager.GetString("Irrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытие.
        /// </summary>
        public static string IsHeatEnabled {
            get {
                return ResourceManager.GetString("IsHeatEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITM, A.
        /// </summary>
        public static string Itm_A {
            get {
                return ResourceManager.GetString("Itm_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозвонка.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За 7 дней.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За месяц.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ток включения.
        /// </summary>
        public static string LatchingCurrent {
            get {
                return ResourceManager.GetString("LatchingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мА.
        /// </summary>
        public static string mA {
            get {
                return ResourceManager.GetString("mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. IDRM, мА.
        /// </summary>
        public static string MaxIdrm_mA {
            get {
                return ResourceManager.GetString("MaxIdrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. IGT, мА.
        /// </summary>
        public static string MaxIgt_mA {
            get {
                return ResourceManager.GetString("MaxIgt_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. IH, мА.
        /// </summary>
        public static string MaxIh_mA {
            get {
                return ResourceManager.GetString("MaxIh_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. IL, мА.
        /// </summary>
        public static string MaxIl_mA {
            get {
                return ResourceManager.GetString("MaxIl_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. IRRM, мА.
        /// </summary>
        public static string MaxIrrm_mA {
            get {
                return ResourceManager.GetString("MaxIrrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. Rg, Ом.
        /// </summary>
        public static string MaxResistance_Ohm {
            get {
                return ResourceManager.GetString("MaxResistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. UGT, В.
        /// </summary>
        public static string MaxVgt_V {
            get {
                return ResourceManager.GetString("MaxVgt_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. UTM, В.
        /// </summary>
        public static string MaxVtm_V {
            get {
                return ResourceManager.GetString("MaxVtm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измерение высоты.
        /// </summary>
        public static string MeasureDialog_Title {
            get {
                return ResourceManager.GetString("MeasureDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. UDRM, В.
        /// </summary>
        public static string MinVdrm_V {
            get {
                return ResourceManager.GetString("MinVdrm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. URRM, В.
        /// </summary>
        public static string MinVrrm_V {
            get {
                return ResourceManager.GetString("MinVrrm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код КИП.
        /// </summary>
        public static string MME_Code {
            get {
                return ResourceManager.GetString("MME_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь КИП и Профилей.
        /// </summary>
        public static string MME_Profiles {
            get {
                return ResourceManager.GetString("MME_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string MME_ProfilesLabel {
            get {
                return ResourceManager.GetString("MME_ProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верно.
        /// </summary>
        public static string NonCorrect {
            get {
                return ResourceManager.GetString("NonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр.
        /// </summary>
        public static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер ЗНП.
        /// </summary>
        public static string PartyNumber {
            get {
                return ResourceManager.GetString("PartyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Годные.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль неверен.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В очереди.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период:.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время, мс.
        /// </summary>
        public static string PlateTime_ms {
            get {
                return ResourceManager.GetString("PlateTime_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция 1.
        /// </summary>
        public static string Position_1 {
            get {
                return ResourceManager.GetString("Position_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция 2.
        /// </summary>
        public static string Position_2 {
            get {
                return ResourceManager.GetString("Position_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки печати:.
        /// </summary>
        public static string PrintingOptions {
            get {
                return ResourceManager.GetString("PrintingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки профилей.
        /// </summary>
        public static string Profile_load_error {
            get {
                return ResourceManager.GetString("Profile_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не могу загрузить профили с сервера компании. Временно используется локальная копия. Ошибка {0}.
        /// </summary>
        public static string Profile_load_error_ex {
            get {
                return ResourceManager.GetString("Profile_load_error_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к базе данных.
        /// </summary>
        public static string ProfileBuilderDBName {
            get {
                return ResourceManager.GetString("ProfileBuilderDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string ProfileBuilderDBPassword {
            get {
                return ResourceManager.GetString("ProfileBuilderDBPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string ProfileBuilderDBUser {
            get {
                return ResourceManager.GetString("ProfileBuilderDBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать интегрированную аутентификацию.
        /// </summary>
        public static string ProfileBuilderIntegratedSecurity {
            get {
                return ResourceManager.GetString("ProfileBuilderIntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите путь к серверу.
        /// </summary>
        public static string ProfileBuilderServerName {
            get {
                return ResourceManager.GetString("ProfileBuilderServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к БД.
        /// </summary>
        public static string ProfileBuilderTitle {
            get {
                return ResourceManager.GetString("ProfileBuilderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя профиля.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отожмите кнопку Стоп.
        /// </summary>
        public static string PullStopButton {
            get {
                return ResourceManager.GetString("PullStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анодный ток.
        /// </summary>
        public static string PureVgt {
            get {
                return ResourceManager.GetString("PureVgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QrrTq.
        /// </summary>
        public static string QrrTq {
            get {
                return ResourceManager.GetString("QrrTq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость спада тока, А/мкс.
        /// </summary>
        public static string QrrTqDCFallRate {
            get {
                return ResourceManager.GetString("QrrTqDCFallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность импульса прямого тока, в мкс.
        /// </summary>
        public static string QrrTqDCPulseWidth {
            get {
                return ResourceManager.GetString("QrrTqDCPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость нарастания прямого тока, А/мкс.
        /// </summary>
        public static string QrrTqDCRiseRate {
            get {
                return ResourceManager.GetString("QrrTqDCRiseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амплитуда прямого тока, А.
        /// </summary>
        public static string QrrTqDirectCurrent {
            get {
                return ResourceManager.GetString("QrrTqDirectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим.
        /// </summary>
        public static string QrrTqMode {
            get {
                return ResourceManager.GetString("QrrTqMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямое повторное напряжение, В.
        /// </summary>
        public static string QrrTqOffStateVoltage {
            get {
                return ResourceManager.GetString("QrrTqOffStateVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость нарастания прямого повторного напр., В/мкс.
        /// </summary>
        public static string QrrTqOsvRate {
            get {
                return ResourceManager.GetString("QrrTqOsvRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измерение Trr по методу 90%-50%.
        /// </summary>
        public static string QrrTqTrrMeasureBy9050Method {
            get {
                return ResourceManager.GetString("QrrTqTrrMeasureBy9050Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R A-C.
        /// </summary>
        public static string RAC {
            get {
                return ResourceManager.GetString("RAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амплитуда напряжения для измерения, В.
        /// </summary>
        public static string RACResVoltage {
            get {
                return ResourceManager.GetString("RACResVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трапеция.
        /// </summary>
        public static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наклон, В/мс.
        /// </summary>
        public static string Rampup_Vms {
            get {
                return ResourceManager.GetString("Rampup_Vms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Только чтение.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брак.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg, Ом.
        /// </summary>
        public static string Resistance_Ohm {
            get {
                return ResourceManager.GetString("Resistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапуск.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратный.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитная цепь разомкнута.
        /// </summary>
        public static string SafetyCircuitIsOpen {
            get {
                return ResourceManager.GetString("SafetyCircuitIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка.
        /// </summary>
        public static string Selftest {
            get {
                return ResourceManager.GetString("Selftest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервис.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полусинус.
        /// </summary>
        public static string Sinus {
            get {
                return ResourceManager.GetString("Sinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовое, В.
        /// </summary>
        public static string StartVoltage_V {
            get {
                return ResourceManager.GetString("StartVoltage_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажата кнопка Стоп.
        /// </summary>
        public static string StopButtonIsPressed {
            get {
                return ResourceManager.GetString("StopButtonIsPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останов.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Номер ППЭ).
        /// </summary>
        public static string StructureName {
            get {
                return ResourceManager.GetString("StructureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Партия ППЭ).
        /// </summary>
        public static string StructureOrder {
            get {
                return ResourceManager.GetString("StructureOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос отправлен.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наладчик.
        /// </summary>
        public static string Technitian {
            get {
                return ResourceManager.GetString("Technitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp, C.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип теста.
        /// </summary>
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время, мкс.
        /// </summary>
        public static string Time_us {
            get {
                return ResourceManager.GetString("Time_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключиться.
        /// </summary>
        public static string TryConnect {
            get {
                return ResourceManager.GetString("TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снять все.
        /// </summary>
        public static string UnCheckAll {
            get {
                return ResourceManager.GetString("UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный диапазон.
        /// </summary>
        public static string UseFullScale {
            get {
                return ResourceManager.GetString("UseFullScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSQ метод.
        /// </summary>
        public static string UseLsqMethod {
            get {
                return ResourceManager.GetString("UseLsqMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оператор.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите профиль.
        /// </summary>
        public static string UserPage_Title {
            get {
                return ResourceManager.GetString("UserPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирование.
        /// </summary>
        public static string UserTestPage_Title {
            get {
                return ResourceManager.GetString("UserTestPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDSM/URSM.
        /// </summary>
        public static string UseUdsmUrsm {
            get {
                return ResourceManager.GetString("UseUdsmUrsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDRM, В.
        /// </summary>
        public static string VdrmV {
            get {
                return ResourceManager.GetString("VdrmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGT.
        /// </summary>
        public static string Vgt {
            get {
                return ResourceManager.GetString("Vgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGT, мВ.
        /// </summary>
        public static string VgtmV {
            get {
                return ResourceManager.GetString("VgtmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGT, В.
        /// </summary>
        public static string VgtV {
            get {
                return ResourceManager.GetString("VgtV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В / мс.
        /// </summary>
        public static string Vms {
            get {
                return ResourceManager.GetString("Vms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напр. прям., В.
        /// </summary>
        public static string VoltageLimitD_V {
            get {
                return ResourceManager.GetString("VoltageLimitD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напр. обрат., В.
        /// </summary>
        public static string VoltageLimitR_V {
            get {
                return ResourceManager.GetString("VoltageLimitR_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URRM, В.
        /// </summary>
        public static string VrrmV {
            get {
                return ResourceManager.GetString("VrrmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стат. потери.
        /// </summary>
        public static string Vtm {
            get {
                return ResourceManager.GetString("Vtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM, В.
        /// </summary>
        public static string VtmV {
            get {
                return ResourceManager.GetString("VtmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение.
        /// </summary>
        public static string WelcomePage_Title {
            get {
                return ResourceManager.GetString("WelcomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
