//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.ProfileBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCME.ProfileBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адаптер.
        /// </summary>
        public static string Adapter {
            get {
                return ResourceManager.GetString("Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. время, мкс.
        /// </summary>
        public static string AdditionalTime_us {
            get {
                return ResourceManager.GetString("AdditionalTime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все модули отключены.
        /// </summary>
        public static string AllUnitsAreDisabled {
            get {
                return ResourceManager.GetString("AllUnitsAreDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при запуске приложения.
        /// </summary>
        public static string ApplicationStartError {
            get {
                return ResourceManager.GetString("ApplicationStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лавина.
        /// </summary>
        public static string Atu {
            get {
                return ResourceManager.GetString("Atu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мощность, кВт.
        /// </summary>
        public static string AtuPowerValueSet {
            get {
                return ResourceManager.GetString("AtuPowerValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда предв. импульса тока, мА.
        /// </summary>
        public static string AtuPrePulseValue {
            get {
                return ResourceManager.GetString("AtuPrePulseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обзор.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классификатор.
        /// </summary>
        public static string Bvt {
            get {
                return ResourceManager.GetString("Bvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Калибровка.
        /// </summary>
        public static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызвать.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно начать тест.
        /// </summary>
        public static string CanNotStartTest {
            get {
                return ResourceManager.GetString("CanNotStartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметить все.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пресс.
        /// </summary>
        public static string Clamp {
            get {
                return ResourceManager.GetString("Clamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закройте защитную заслонку.
        /// </summary>
        public static string CloseSafetyHood {
            get {
                return ResourceManager.GetString("CloseSafetyHood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Блок коммутации.
        /// </summary>
        public static string Commutation {
            get {
                return ResourceManager.GetString("Commutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммутация.
        /// </summary>
        public static string CommutationType {
            get {
                return ResourceManager.GetString("CommutationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип коммутации.
        /// </summary>
        public static string CommutationTypeT {
            get {
                return ResourceManager.GetString("CommutationTypeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Консоль.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верно.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ток, А.
        /// </summary>
        public static string Current_A {
            get {
                return ResourceManager.GetString("Current_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ток, мА.
        /// </summary>
        public static string CurrentLimit_mA {
            get {
                return ResourceManager.GetString("CurrentLimit_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на S-кривая.
        /// </summary>
        public static string Curve {
            get {
                return ResourceManager.GetString("Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коэффициент.
        /// </summary>
        public static string CurveFactor {
            get {
                return ResourceManager.GetString("CurveFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказчик:.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип п-ра:.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сер. номер прибора.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямой.
        /// </summary>
        public static string Direct {
            get {
                return ResourceManager.GetString("Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключить.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключен.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дисплей.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таймаут дисплея.
        /// </summary>
        public static string DisplayTimeout {
            get {
                return ResourceManager.GetString("DisplayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зажать.
        /// </summary>
        public static string DoClamp {
            get {
                return ResourceManager.GetString("DoClamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разжать.
        /// </summary>
        public static string DoUnclamp {
            get {
                return ResourceManager.GetString("DoUnclamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dVdt.
        /// </summary>
        public static string dVdt {
            get {
                return ResourceManager.GetString("dVdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверджение.
        /// </summary>
        public static string DvdtConfirmation {
            get {
                return ResourceManager.GetString("DvdtConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число подтверждений.
        /// </summary>
        public static string DvdtConfirmationCount {
            get {
                return ResourceManager.GetString("DvdtConfirmationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определение.
        /// </summary>
        public static string DvdtDetection {
            get {
                return ResourceManager.GetString("DvdtDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напряжение, В.
        /// </summary>
        public static string DvDtVoltage {
            get {
                return ResourceManager.GetString("DvDtVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скор. роста, В/мкс.
        /// </summary>
        public static string DvdtVoltageRate {
            get {
                return ResourceManager.GetString("DvdtVoltageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Огр. скор. роста, В/мкс.
        /// </summary>
        public static string DvdtVoltageRateLimit {
            get {
                return ResourceManager.GetString("DvdtVoltageRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (+) к скор. роста, В/мкс.
        /// </summary>
        public static string DvdtVoltageRateOffSet {
            get {
                return ResourceManager.GetString("DvdtVoltageRateOffSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключить.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении конфигурационного файла профилей.
        /// </summary>
        public static string ErrorWhileProfileParsing {
            get {
                return ResourceManager.GetString("ErrorWhileProfileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка отправки.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Усилие, кН.
        /// </summary>
        public static string Force {
            get {
                return ResourceManager.GetString("Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота имп., Гц.
        /// </summary>
        public static string FreqRate_Hz {
            get {
                return ResourceManager.GetString("FreqRate_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота, Гц.
        /// </summary>
        public static string Frequency_Hz {
            get {
                return ResourceManager.GetString("Frequency_Hz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление.
        /// </summary>
        public static string Gate {
            get {
                return ResourceManager.GetString("Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шлюз.
        /// </summary>
        public static string Gateway {
            get {
                return ResourceManager.GetString("Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I, мА.
        /// </summary>
        public static string Graph_ImA {
            get {
                return ResourceManager.GetString("Graph_ImA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время, мс.
        /// </summary>
        public static string Graph_TimeMs {
            get {
                return ResourceManager.GetString("Graph_TimeMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время, мкс.
        /// </summary>
        public static string Graph_TimeUs {
            get {
                return ResourceManager.GetString("Graph_TimeUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на U.
        /// </summary>
        public static string Graph_V {
            get {
                return ResourceManager.GetString("Graph_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на U, I.
        /// </summary>
        public static string Graph_VI {
            get {
                return ResourceManager.GetString("Graph_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список партий.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аппаратная часть.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ток откр., А.
        /// </summary>
        public static string HeatCurrent_A {
            get {
                return ResourceManager.GetString("HeatCurrent_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время откр., мкс.
        /// </summary>
        public static string HeatTime_us {
            get {
                return ResourceManager.GetString("HeatTime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота, мм.
        /// </summary>
        public static string Height_Prof {
            get {
                return ResourceManager.GetString("Height_Prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ток удержания.
        /// </summary>
        public static string HoldingCurrent {
            get {
                return ResourceManager.GetString("HoldingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. импульс.
        /// </summary>
        public static string HoldingStrikeCurrent {
            get {
                return ResourceManager.GetString("HoldingStrikeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IDRM, мА.
        /// </summary>
        public static string Idrm_mA {
            get {
                return ResourceManager.GetString("Idrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IGT, мА.
        /// </summary>
        public static string Igt_mA {
            get {
                return ResourceManager.GetString("Igt_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ih, мА.
        /// </summary>
        public static string Iholding_mA {
            get {
                return ResourceManager.GetString("Iholding_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Il, мА.
        /// </summary>
        public static string Ilatching_mA {
            get {
                return ResourceManager.GetString("Ilatching_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IRRM, мА.
        /// </summary>
        public static string Irrm_mA {
            get {
                return ResourceManager.GetString("Irrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие.
        /// </summary>
        public static string IsHeatEnabled {
            get {
                return ResourceManager.GetString("IsHeatEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ITM, A.
        /// </summary>
        public static string Itm_A {
            get {
                return ResourceManager.GetString("Itm_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прозвонка.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За 7 дней.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За месяц.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ток включения.
        /// </summary>
        public static string LatchingCurrent {
            get {
                return ResourceManager.GetString("LatchingCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логи.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мА.
        /// </summary>
        public static string mA {
            get {
                return ResourceManager.GetString("mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. IDRM, мА.
        /// </summary>
        public static string MaxIdrm_mA {
            get {
                return ResourceManager.GetString("MaxIdrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. IGT, мА.
        /// </summary>
        public static string MaxIgt_mA {
            get {
                return ResourceManager.GetString("MaxIgt_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. IH, мА.
        /// </summary>
        public static string MaxIh_mA {
            get {
                return ResourceManager.GetString("MaxIh_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. IL, мА.
        /// </summary>
        public static string MaxIl_mA {
            get {
                return ResourceManager.GetString("MaxIl_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. IRRM, мА.
        /// </summary>
        public static string MaxIrrm_mA {
            get {
                return ResourceManager.GetString("MaxIrrm_mA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. Rg, Ом.
        /// </summary>
        public static string MaxResistance_Ohm {
            get {
                return ResourceManager.GetString("MaxResistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. UGT, В.
        /// </summary>
        public static string MaxVgt_V {
            get {
                return ResourceManager.GetString("MaxVgt_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. UTM, В.
        /// </summary>
        public static string MaxVtm_V {
            get {
                return ResourceManager.GetString("MaxVtm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерение высоты.
        /// </summary>
        public static string MeasureDialog_Title {
            get {
                return ResourceManager.GetString("MeasureDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мин. UDRM, В.
        /// </summary>
        public static string MinVdrm_V {
            get {
                return ResourceManager.GetString("MinVdrm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мин. URRM, В.
        /// </summary>
        public static string MinVrrm_V {
            get {
                return ResourceManager.GetString("MinVrrm_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код КИП.
        /// </summary>
        public static string MME_Code {
            get {
                return ResourceManager.GetString("MME_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Связь КИП и Профилей.
        /// </summary>
        public static string MME_Profiles {
            get {
                return ResourceManager.GetString("MME_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профили.
        /// </summary>
        public static string MME_ProfilesLabel {
            get {
                return ResourceManager.GetString("MME_ProfilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Далее.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верно.
        /// </summary>
        public static string NonCorrect {
            get {
                return ResourceManager.GetString("NonCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОК.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр.
        /// </summary>
        public static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер ЗНП.
        /// </summary>
        public static string PartyNumber {
            get {
                return ResourceManager.GetString("PartyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Годные.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль неверен.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В очереди.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период:.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время, мс.
        /// </summary>
        public static string PlateTime_ms {
            get {
                return ResourceManager.GetString("PlateTime_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция 1.
        /// </summary>
        public static string Position_1 {
            get {
                return ResourceManager.GetString("Position_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция 2.
        /// </summary>
        public static string Position_2 {
            get {
                return ResourceManager.GetString("Position_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки печати:.
        /// </summary>
        public static string PrintingOptions {
            get {
                return ResourceManager.GetString("PrintingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профили.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки профилей.
        /// </summary>
        public static string Profile_load_error {
            get {
                return ResourceManager.GetString("Profile_load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не могу загрузить профили с сервера компании. Временно используется локальная копия. Ошибка {0}.
        /// </summary>
        public static string Profile_load_error_ex {
            get {
                return ResourceManager.GetString("Profile_load_error_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к базе данных.
        /// </summary>
        public static string ProfileBuilderDBName {
            get {
                return ResourceManager.GetString("ProfileBuilderDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string ProfileBuilderDBPassword {
            get {
                return ResourceManager.GetString("ProfileBuilderDBPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string ProfileBuilderDBUser {
            get {
                return ResourceManager.GetString("ProfileBuilderDBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать интегрированную аутентификацию.
        /// </summary>
        public static string ProfileBuilderIntegratedSecurity {
            get {
                return ResourceManager.GetString("ProfileBuilderIntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите путь к серверу.
        /// </summary>
        public static string ProfileBuilderServerName {
            get {
                return ResourceManager.GetString("ProfileBuilderServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к БД.
        /// </summary>
        public static string ProfileBuilderTitle {
            get {
                return ResourceManager.GetString("ProfileBuilderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя профиля.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отожмите кнопку Стоп.
        /// </summary>
        public static string PullStopButton {
            get {
                return ResourceManager.GetString("PullStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анодный ток.
        /// </summary>
        public static string PureVgt {
            get {
                return ResourceManager.GetString("PureVgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на QrrTq.
        /// </summary>
        public static string QrrTq {
            get {
                return ResourceManager.GetString("QrrTq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость спада тока, А/мкс.
        /// </summary>
        public static string QrrTqDCFallRate {
            get {
                return ResourceManager.GetString("QrrTqDCFallRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длительность импульса прямого тока, в мкс.
        /// </summary>
        public static string QrrTqDCPulseWidth {
            get {
                return ResourceManager.GetString("QrrTqDCPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость нарастания прямого тока, А/мкс.
        /// </summary>
        public static string QrrTqDCRiseRate {
            get {
                return ResourceManager.GetString("QrrTqDCRiseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда прямого тока, А.
        /// </summary>
        public static string QrrTqDirectCurrent {
            get {
                return ResourceManager.GetString("QrrTqDirectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим.
        /// </summary>
        public static string QrrTqMode {
            get {
                return ResourceManager.GetString("QrrTqMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямое повторное напряжение, В.
        /// </summary>
        public static string QrrTqOffStateVoltage {
            get {
                return ResourceManager.GetString("QrrTqOffStateVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость нарастания прямого повторного напр., В/мкс.
        /// </summary>
        public static string QrrTqOsvRate {
            get {
                return ResourceManager.GetString("QrrTqOsvRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерение Trr по методу 90%-50%.
        /// </summary>
        public static string QrrTqTrrMeasureBy9050Method {
            get {
                return ResourceManager.GetString("QrrTqTrrMeasureBy9050Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R A-C.
        /// </summary>
        public static string RAC {
            get {
                return ResourceManager.GetString("RAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда напряжения для измерения, В.
        /// </summary>
        public static string RACResVoltage {
            get {
                return ResourceManager.GetString("RACResVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трапеция.
        /// </summary>
        public static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наклон, В/мс.
        /// </summary>
        public static string Rampup_Vms {
            get {
                return ResourceManager.GetString("Rampup_Vms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  - Только чтение.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брак.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rg, Ом.
        /// </summary>
        public static string Resistance_Ohm {
            get {
                return ResourceManager.GetString("Resistance_Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапуск.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратный.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Защитная цепь разомкнута.
        /// </summary>
        public static string SafetyCircuitIsOpen {
            get {
                return ResourceManager.GetString("SafetyCircuitIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка.
        /// </summary>
        public static string Selftest {
            get {
                return ResourceManager.GetString("Selftest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полусинус.
        /// </summary>
        public static string Sinus {
            get {
                return ResourceManager.GetString("Sinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стартовое, В.
        /// </summary>
        public static string StartVoltage_V {
            get {
                return ResourceManager.GetString("StartVoltage_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажата кнопка Стоп.
        /// </summary>
        public static string StopButtonIsPressed {
            get {
                return ResourceManager.GetString("StopButtonIsPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Останов.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Номер ППЭ).
        /// </summary>
        public static string StructureName {
            get {
                return ResourceManager.GetString("StructureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Партия ППЭ).
        /// </summary>
        public static string StructureOrder {
            get {
                return ResourceManager.GetString("StructureOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос отправлен.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наладчик.
        /// </summary>
        public static string Technitian {
            get {
                return ResourceManager.GetString("Technitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temp, C.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип теста.
        /// </summary>
        public static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время, мкс.
        /// </summary>
        public static string Time_us {
            get {
                return ResourceManager.GetString("Time_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сила тока (ITM),  А.
        /// </summary>
        public static string TOUITM {
            get {
                return ResourceManager.GetString("TOUITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться.
        /// </summary>
        public static string TryConnect {
            get {
                return ResourceManager.GetString("TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снять все.
        /// </summary>
        public static string UnCheckAll {
            get {
                return ResourceManager.GetString("UnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный диапазон.
        /// </summary>
        public static string UseFullScale {
            get {
                return ResourceManager.GetString("UseFullScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LSQ метод.
        /// </summary>
        public static string UseLsqMethod {
            get {
                return ResourceManager.GetString("UseLsqMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите профиль.
        /// </summary>
        public static string UserPage_Title {
            get {
                return ResourceManager.GetString("UserPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестирование.
        /// </summary>
        public static string UserTestPage_Title {
            get {
                return ResourceManager.GetString("UserTestPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UDRM, В.
        /// </summary>
        public static string VdrmV {
            get {
                return ResourceManager.GetString("VdrmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UGT.
        /// </summary>
        public static string Vgt {
            get {
                return ResourceManager.GetString("Vgt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UGT, мВ.
        /// </summary>
        public static string VgtmV {
            get {
                return ResourceManager.GetString("VgtmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UGT, В.
        /// </summary>
        public static string VgtV {
            get {
                return ResourceManager.GetString("VgtV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В / мс.
        /// </summary>
        public static string Vms {
            get {
                return ResourceManager.GetString("Vms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напр. прям., В.
        /// </summary>
        public static string VoltageLimitD_V {
            get {
                return ResourceManager.GetString("VoltageLimitD_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напр. обрат., В.
        /// </summary>
        public static string VoltageLimitR_V {
            get {
                return ResourceManager.GetString("VoltageLimitR_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URRM, В.
        /// </summary>
        public static string VrrmV {
            get {
                return ResourceManager.GetString("VrrmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стат. потери.
        /// </summary>
        public static string Vtm {
            get {
                return ResourceManager.GetString("Vtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UTM, В.
        /// </summary>
        public static string VtmV {
            get {
                return ResourceManager.GetString("VtmV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение.
        /// </summary>
        public static string WelcomePage_Title {
            get {
                return ResourceManager.GetString("WelcomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вчера.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
