//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.SQLDatabaseClient.EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities(string connString)
            : base(connString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEVICE> DEVICES { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<DEV_PARAM> DEV_PARAM { get; set; }
        public virtual DbSet<ERROR> ERRORS { get; set; }
        public virtual DbSet<PARAM> PARAMS { get; set; }
        public virtual DbSet<CONDITION> CONDITIONS { get; set; }
        public virtual DbSet<PROF_COND> PROF_COND { get; set; }
        public virtual DbSet<PROF_PARAM> PROF_PARAM { get; set; }
        public virtual DbSet<PROF_TEST_TYPE> PROF_TEST_TYPE { get; set; }
        public virtual DbSet<PROFILE> PROFILES { get; set; }
        public virtual DbSet<TEST_TYPE> TEST_TYPE { get; set; }
    }
}
