//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.SQLDatabaseClient.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROFILE()
        {
            this.PROF_COND = new HashSet<PROF_COND>();
            this.PROF_PARAM = new HashSet<PROF_PARAM>();
            this.PROF_TEST_TYPE = new HashSet<PROF_TEST_TYPE>();
        }
    
        public int PROF_ID { get; set; }
        public string PROF_NAME { get; set; }
        public System.Guid PROF_GUID { get; set; }
        public System.DateTime PROF_TS { get; set; }
        public int PROF_VERS { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROF_COND> PROF_COND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROF_PARAM> PROF_PARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROF_TEST_TYPE> PROF_TEST_TYPE { get; set; }
    }
}
