//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.SQLDatabaseClient.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROF_COND
    {
        public int PROF_TESTTYPE_ID { get; set; }
        public int PROF_ID { get; set; }
        public int COND_ID { get; set; }
        public string VALUE { get; set; }
    
        public virtual CONDITION CONDITION { get; set; }
        public virtual PROF_TEST_TYPE PROF_TEST_TYPE { get; set; }
        public virtual PROFILE PROFILE { get; set; }
    }
}
