//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCME.SQLDatabaseClient.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEST_TYPE()
        {
            this.PROF_TEST_TYPE = new HashSet<PROF_TEST_TYPE>();
        }
    
        public int TEST_TYPE_ID { get; set; }
        public string TEST_TYPE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROF_TEST_TYPE> PROF_TEST_TYPE { get; set; }
    }
}
